---
- name: Create 3 Tier App
  hosts: apic
  connection: local
  gather_facts: no

  vars:
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic_username }}'
      password: '{{ apic_password }}'
      use_proxy: no
      validate_certs: no
    tenant: CiscoLive
    vrf: VRF1
    bd:
      name: BD-Web
      gateway: 192.168.1.254
      mask: 24
    ap: APP1
    epg1: Web
    vmmdomain: ACI-vDS

  tasks:
    - name: TASK 01 - Create Tenant
      aci_tenant:
        <<: *aci_login
        tenant: "{{ tenant }}"

    - name: TASK 02 - Create VRF
      aci_vrf:
        <<: *aci_login
        tenant: "{{ tenant }}"
        vrf: "{{ vrf }}"

    - name: TASK 03 - Create BD
      aci_bd:
        <<: *aci_login
        tenant: "{{ tenant }}"
        bd: "{{ bd.name }}"
        vrf: "{{ vrf }}"
        enable_routing: yes
        arp_flooding: yes
        l2_unknown_unicast: flood

    - name: TASK 04 - Create BD subnet
      aci_bd_subnet:
        <<: *aci_login
        tenant: "{{ tenant }}"
        bd: "{{ bd.name }}"
        gateway: "{{ bd.gateway }}"
        mask: "{{ bd.mask }}"
        scope: public

    - name: TASK 05 - Create AP
      aci_ap:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"

    - name: TASK 06 - Create EPG
      aci_epg:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ epg1 }}"
        bd: "{{ bd.name }}"

    - name: TASK 07 - Associate EPG to domain
      aci_epg_to_domain:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ epg1 }}"
        domain: "{{ vmmdomain }}"
        domain_type: "vmm"
        vm_provider: "vmware"
        encap_mode: "auto"
